### ISSUE TITLE
Documentation says height can be a string, but according to propType it can't

### ISSUE THREAD

**Issue by denis-isaev** [clauderic/react-tiny-virtual-list#13]
Documentation says height can be a string when horizontal scrollMode selected, but propTypes for height is 
```javascript
height: PropTypes.number.isRequired
```

**Comment by clauderic** [comment]
Ah yes, you're absolutely right, thanks for pointing this out!

**Comment by clauderic** [comment]
Fixed in `react-tiny-virtual-list@2.0.6`
