### ISSUE TITLE
Get index of top/last visible element on scroll

### ISSUE THREAD

**Issue by error-yatish** [clauderic/react-tiny-virtual-list#14]
Here on **onScroll** event we're getting `top, event` in callback function.
Is there any way to get the `index` of **Top or Bottom** visible element? 

something like
```
onScroll(top, event, topIndex, bottomIndex){

}
```

**Comment by clauderic** [comment]
Hmm, probably not as a callback `onScroll`, but rather as a `onItemsRendered` prop. Something along these lines: https://github.com/clauderic/virtualized-list/blob/master/src/VirtualList/index.js#L160-L163

I should get around to it in the not so distant future, but if you have a pressing need for this, I'd be happy to accept a PR along those lines, with updated docs on how to use that prop.

**Comment by error-yatish** [comment]
Thank you @clauderic 
We'll review it and let you know If get time to create PR.
Thanks.

**Comment by clauderic** [comment]
Just shipped version `2.1.1` with a new `onItemsRendered` prop. 

The `onItemsRendered` prop is a callback invoked with information about the slice of rows/columns that were just rendered. It has the following signature: ({startIndex: number, stopIndex: number}).

Let me know if you run into any issues 👍
