### ISSUE TITLE
After set scrollToIndex, itemSize of previous indexes get wrong (Using previously cached item)

### ISSUE THREAD

**Issue by error-yatish** [clauderic/react-tiny-virtual-list#16]
Here is my code snippet
``` javascript
In Render

        let { collections } = this.props;
       
        console.log( collections[2].isCollapse, 'collapsed');  // will print **true** (it was **false** previously but changed to **true** by dispatching action)

        let calculateItemSize = (i)=> {

            console.log(i, collections[2].isCollapse, 'collapsed') // will print **false** 

            let minLength = 1;
            if(collections[i].tabs.length){
                minLength = collections[i].tabs.length;
            }
            return collections[i].isCollapse ? (Math.round(minLength / 2) * 50) + 100 : 70;
        }

<VirtualList
     itemSize={ calculateItemSize }
     scrollToIndex={ 5 }
     ...
/>
```

I'm collapsing the div and accordingly height also get changed in virtual list, now what happen here is height works fine when starting index starts from 0 but once I set `scrollToIndex=5` then item from index 0 to 5 will behave totally opposite in nature. like open collapse with reduced height and close will increase height.

By debugging the library I found that after set manual scroll index It will use previous cached data to manipulate `itemSize` logic. please review the above code snippet with comment.

thank you :)

**Comment by clauderic** [comment]
Hey @error-yatish,

It's difficult for me to help you just based on the code you've pasted above, I'd need to see more. Are you able to put together a repro case I can look at on https://www.webpackbin.com/?

Have you tried using the [`recomputeSizes` instance method](https://github.com/clauderic/react-tiny-virtual-list#recomputesizes-index-number)?

**Comment by 10S10** [comment]
@clauderic I think `recomputeSizes` should work. 
But I'm unsure that how to use it. Can you please help me? Should I need to import something or can directly call this public method?

**Comment by clauderic** [comment]
You need to store a [ref](https://facebook.github.io/react/docs/refs-and-the-dom.html#adding-a-ref-to-a-class-component) to the `VirtualList` component.

```
class MyComponent extends React.Component {
	resizeItems() {
		this.virtualList.recomputeSizes();
	}
  render() {
    return (
			<VirtualList
				ref={(instance) => {
					this.virtualList = instance;
				}}
			/>
		)
  }
}
```
