### ISSUE TITLE
support scrollToIndexIfNecessary?

### ISSUE THREAD

**Issue by kentcdodds** [clauderic/react-tiny-virtual-list#19]
I'm trying to support `react-tiny-virtual-list` in a nice way in [`downshift`](https://github.com/paypal/downshift) and it would be very helpful if there were a way to have `react-tiny-virtual-list` only scroll to an index if that node is not currently visible.

See [this example](https://github.com/paypal/downshift/blob/master/stories/examples/windowing-with-react-tiny-virtual-list.js) and the [live demo here](http://downshift.netlify.com/?selectedKind=Examples&selectedStory=windowing%20with%20react-tiny-virtual-list&full=0&down=1&left=1&panelRight=0).

Thanks!

**Comment by clauderic** [comment]
Hey @kentcdodds, 

Sorry for the late response. Completely missed this somehow 🤷‍♂️ 

I hadn't thought of that particular use case, but I'm sure it's a fairly common one so it would absolutely make sense to support this 👍 

I think this behaviour can be handled by slightly tweaking the implementation of `scrollToAlignment`. Something like `scrollToAlignment="auto"`.

**Comment by kentcdodds** [comment]
That sounds great :+1: Thanks!

Can't wait to update my example.

**Comment by clauderic** [comment]
Just shipped `scrollToAlignment="auto"` with version `2.1.0`. 'auto' scrolls the least amount possible to ensure that the specified scrollToIndex item is fully visible, which should be the behaviour you're looking for. Let me know how that goes 👍

**Comment by kentcdodds** [comment]
Thank you! [It works great!](https://codesandbox.io/s/o5yk7pzmmy)

**Comment by kentcdodds** [comment]
Whoops, wrong link. Here's the right one: https://codesandbox.io/s/v670kq95l

**Comment by clauderic** [comment]
Looks awesome 🤓 🎉
