### ISSUE TITLE
es.js in build directory breaks webpack compilation

### ISSUE THREAD

**Issue by evanjmg** [clauderic/react-tiny-virtual-list#22]
ERROR in main.bundle.js from UglifyJs
Unexpected token: punc ([) [./~/react-tiny-virtual-list/build/react-tiny-virtual-list.es.js:43,0][main.bundle.js:25816,4]

Please remove this - even with the latest uglifyJs webpack plugin with es6 support it fails

**Comment by clauderic** [comment]
Hmm sorry about that, I'll investigate and get back to you.

**Comment by clauderic** [comment]
Should be fixed in `2.1.2`, sorry about that!
