### ISSUE TITLE
TypeScript definition files as part of NPM package

### ISSUE THREAD

**Issue by SimplerSoftware** [clauderic/react-tiny-virtual-list#26]
First off - great work!!!  I'd like to use this library with TypeScript, and seeing how it appears that it was recently migrated to TypeScript would you please include the TypeScript definition file as part of the NPM package?

**Comment by clauderic** [comment]
Sorry completely missed that somehow, the idea was to have the types as part of the package, yes 😅 

I think I just need to update the package.json `files` entry to include the `types` folder that gets generated at build time.

I'll take a look and get back to you 😄

**Comment by clauderic** [comment]
I've just released `2.1.3` which should include the types file, let me know if it works out for you 👍

**Comment by SimplerSoftware** [comment]
It's there now.  Thanks!
