### ISSUE TITLE
Dynamic inserting does not work

### ISSUE THREAD

**Issue by garetmckinley** [clauderic/react-tiny-virtual-list#3]
I have a reproduction of the issue here: https://www.webpackbin.com/bins/-KgWJv_0IC1-9cyvzud8

As you can see from the comment inside `Hello.js`, the list only renders the items initially populated inside the provided list. If you update that list after the `VirtualList` is rendered, it does not re-render to reflect those changes.

I'm trying to use this component for an insert-heavy project, does this library not support dynamic inserting? If not, is this something you are wanting to support?

**Comment by clauderic** [comment]
Hey @garetmckinley!

Talked with @zsherman, this is definitely an oversight, thanks for pointing it out and putting a repro case together. Thankfully it's a fairly straightforward fix, should be shipping an update shortly, stay tuned.

**Comment by clauderic** [comment]
Fixed via c30081c528fb1e78a2af6ec02c1b6e84f697473c and just published `2.0.2` to npm, let me know if you run into any other issues 👍

**Comment by garetmckinley** [comment]
Wow that was fast, well done man :fire: and great work on the lib! Is it alright if I dm you on twitter with questions (if I have any)?

**Comment by clauderic** [comment]
Yeah absolutely, don't hesitate if you do, and thanks for the kind words ❤️
