### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by steipete** [clauderic/react-tiny-virtual-list#31]
Hi there and thanks for this great project!

We have a script that scans for licenses and if you'd add a `LICENSE` file with the actual MIT license that would make our life a lot easier! I can open a PR as well but figured you might want to do that yourself to be the creator of that one.

Thanks!

**Comment by clauderic** [comment]
Fixed 👍  Could've sworn I had created one for this project.

**Comment by steipete** [comment]
Awesome - thank you! 👌
