### ISSUE TITLE
not support commonjs require syntax

### ISSUE THREAD

**Issue by ikzjfr0** [clauderic/react-tiny-virtual-list#32]
I tried to include it with require syntax like: 
```const VirtualList = require('react-tiny-virtual-list');```

then use it in render method
```
render() {
    return (
      <div className="Root">
        <VirtualList
          width="auto"
          height={400}
          itemCount={1000}
          renderItem={this.renderItem}
          itemSize={50}
          className="VirtualList"
        />
      </div>
    );
  }
```

And got the following error from Chrome logs:
```warning.js:33 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.```

**Comment by clauderic** [comment]
Try `const VirtualList = require('react-tiny-virtual-list').default;`
