### ISSUE TITLE
List doesn't re-render on sorting of the data.

### ISSUE THREAD

**Issue by kakadiadarpan** [clauderic/react-tiny-virtual-list#34]
I'm using react-tiny-virtual-list to show a list which can be sorted. On sorting the data, there is no effect on the rendered list. But when I scroll, the list gets re-rendered.

**Comment by clauderic** [comment]
`List` uses [PureComponent](https://reactjs.org/docs/react-api.html#reactpurecomponent), so it only update when it's props change. You can force it to re-render by calling [forceUpdate](https://reactjs.org/docs/react-component.html#forceupdate) on it or by passing it an extra prop that will change every time your data changes.

**Comment by kakadiadarpan** [comment]
Thanks for the info. I think this is something that should be there in the documentation.
