### ISSUE TITLE
scrollToIndex and itemSize (caching?) issues

### ISSUE THREAD

**Issue by giuseppeg** [clauderic/react-tiny-virtual-list#40]
Hi thanks for this awesome library!

I am experiencing an odd issue (possibly a bug). When using `scrollToIndex` and resizing a (vertical) list the row styles seem to be incorrect. Specifically `height` and `top` seem to be wrong. 

I prepared a simple testcase for you to try out https://codesandbox.io/s/3wm42q716 
When clicking the 💥 button the list resizes (`itemSize` changes) and the `height` of all rows up to the `scrollToIndex` are wrong.

Do you have any idea of what it is going on?

**Comment by giuseppeg** [comment]
Resetting `this.lastMeasuredIndex` to `-1` here https://github.com/clauderic/react-tiny-virtual-list/blob/master/src/SizeAndPositionManager.ts#L88 works obviously

**Comment by clauderic** [comment]
Hmm, looks like a legitimate issue, would you care to send a PR that fixes this? 😄

**Comment by giuseppeg** [comment]
@clauderic I just realized that I completely forgot to reply to your last question, I am sorry about that. Thank you so much for taking the time to fix this <3
