### ISSUE TITLE
Animate added/removed/updated items in list?

### ISSUE THREAD

**Issue by oskarer** [clauderic/react-tiny-virtual-list#43]
It would be really neat to be able to use this together with https://reactcommunity.org/react-transition-group/ or some other solution that mimics this behavior.

Do you think it would be possible to do such a thing with this library, and can you point me in the right direction? If so I can try implementing it and submit a PR.

**Comment by clauderic** [comment]
This is likely feasible using react-transition-group, yes, though this isn't something I've attempted myself.
