### ISSUE TITLE
Error when running dev

### ISSUE THREAD

**Issue by oskarer** [clauderic/react-tiny-virtual-list#44]
<img width="834" alt="image" src="https://user-images.githubusercontent.com/4076953/36788349-e7b1f94c-1c8d-11e8-964f-a1c93da00520.png">

Node: 8.9.1
npm: 5.5.1
tsc: 2.7.2

Doing clean install;
```
$ git clone git@github.com:clauderic/react-tiny-virtual-list.git
$ cd react-tiny-virtual-list
$ npm install
$ npm start
```

**Comment by clauderic** [comment]
Try installing with `yarn`
