### ISSUE TITLE
className support [feature request]

### ISSUE THREAD

**Issue by damianobarbati** [clauderic/react-tiny-virtual-list#51]
I was trying to hide/style scrollbars on Windows/Chrome but I noticed that my className is swallowed and not applied!

```
    //in @injectSheet
    tbody: {
        width: '100%',
        '&::-webkit-scrollbar': {
            width: 0, // remove scrollbar space
            background: 'transparent', // make scrollbar invisible
        },
    },

   //in render
        <VirtualList
            id={'tableBody'}
            className={classes.tbody} //my class with styles for scrollbars here in classes.tbody
            height={tbodyHeight}
            ....
```

**Comment by clauderic** [comment]
The `className` prop is passed through to the wrapper container, along with all other extra attributes https://github.com/clauderic/react-tiny-virtual-list/blob/master/src/index.tsx#L313

You must be having issues with your CSS-in-JS library.

**Comment by damianobarbati** [comment]
Yes you're right, I just confirmed it and I was about to close this. Sorry for the noise!
