### ISSUE TITLE
I have to force render the list again, if the list item heights are dynamic

### ISSUE THREAD

**Issue by marsonmao** [clauderic/react-tiny-virtual-list#52]
1. The list item heights are dynamic and are only known after their first render, so I collect the heights in the list item `componentDidMount()` and cache the heights.
2. The list props `itemSize={this.getItemSize}` returns the cached heights.
3. However `itemSize` is invoked before step 1 (it is invoked inside `this.getStyle(index)`), so the first list render gets the wrong height.
4. So I now have to do `recomputeSizes()` and `forceUpdate()` in the list `componentDidUpdate` to trigger `itemSize` again, so that the correct height could be used.
5. The list items are like varying length texts and images; I'm building a chat history list.

**The question: is this necessary? I'd like to know if it's a must to always render twice since the item height can't be known in the first render?**

My codes are below for reference:

```
  componentDidUpdate(prevProps, prevState, snapshot) {
    //...based on some conditions I do the following
    this.li.recomputeSizes();
    this.li.forceUpdate();
  }
  getItemSize = (index) => {
    const { chatObjects } = this.props;
    const chatObject = chatObjects[index];
    return this.heightCache[chatObject.messageId] || 40;
  }
  renderItem = ({ index, style }) => {
    const { chatObjects } = this.props;
    const chatObject = chatObjects[index];
    return (
      <div key={chatObject.messageId} style={style}>
        <ChatObject
          key={chatObject.messageId}
          chatObject={chatObject}
          onDidMount={(height) => { this.heightCache[chatObject.messageId] = height; }}
          onDidUpdate={(height) => { this.heightCache[chatObject.messageId] = height; }}
        />
      </div>
    );
  }
  render() {
    return (
          <VirtualList
            ref={this.addVirtualList}
            width={width}
            height={height}
            itemCount={chatObjects.length}
            itemSize={this.getItemSize}
            renderItem={this.renderItem}
            onItemsRendered={this.onItemsRendered}
            onScroll={this.onScroll}
            {...scrollToIndex}
            overscanCount={20}
          />
    );
  }
```

**Comment by clauderic** [comment]
`react-tiny-virtual-list` uses [PureComponent](https://github.com/clauderic/react-tiny-virtual-list#common-issues-with-purecomponent), and as such, it has no way to know when the sizes of your items changes when you use a function to get the item sizes.

You can call `forceUpdate` on the instance or pass it an extra prop that changes whenever the size of your items changes. 

See https://github.com/clauderic/react-tiny-virtual-list#common-issues-with-purecomponent
