### ISSUE TITLE
Sticky rows

### ISSUE THREAD

**Issue by jeroenransijn** [clauderic/react-tiny-virtual-list#53]
This project has been super helpful implementing virtualization in our React UI Framework (http://evergreen.surge.sh/).

Recently we wanted to create a select menu with grouped options:  https://github.com/segmentio/evergreen/pull/190
![image](https://user-images.githubusercontent.com/564463/41803858-725cb812-7642-11e8-8594-ed2fdfd5e5b1.png)

I flatten the options and things work fine. However the usability drawback is that the option headers are not sticky at the top of the list. They scroll like any other item.

I am currently exploring two options, either biting the bullet and using `react-virtualized`. Or, extend `react-tiny-virtual-list`. Or, find a different solution all together.

I understand wanting to keep the API simple and focused, I was wondering  if this seems like a reasonable thing to extend in `react-tiny-virtual-list`. If that is the case, I will dig deeper into the code and see how to implement it.

**Comment by clauderic** [comment]
Hey @jeroenransijn,

Didn't know you guys were using `react-tiny-virtual-list` in Evergreen, that's pretty cool 😄 

The use case you described is actually something I've done in the past for a side project using `react-tiny-virtual-list`, but I never spent the time to properly open source that feature. Here's what it looks like.

The solution I came up to solve that use case relies on `position: sticky`, so it will only work in browsers that support that feature, but will degrade gracefully for other browsers.

<img src="https://user-images.githubusercontent.com/1416436/41815604-4288c804-773e-11e8-9a0c-32bb6a1735f7.gif" width="350" />

To use it, you would simply have to pass in a `stickyIndices` prop with an array of all the items that should be made sticky (eg, `stickyIndices={[0, 20, 30, 50, 150]}`)

If you want to try it out, here's the PR (still WIP): https://github.com/clauderic/react-tiny-virtual-list/pull/55

**Comment by jeroenransijn** [comment]
@clauderic that is exactly what I was hoping for! I will take a look at your PR.

**Comment by ghost** [comment]
what about sticky to bottom items?
