### ISSUE TITLE
[Question] Max height div

### ISSUE THREAD

**Issue by jeroenransijn** [clauderic/react-tiny-virtual-list#62]
I am running some tests as to render lists with 100k–1m rows. It seems that browsers have a max height for divs: `1.67771e+07px` for me on Chrome Mac. It seems that `react-virtualized` somehow handles it. This is very much an edge-case, but just curious if anyone is aware of this? Feel free to close issue.

`1.67771e+07px` => `16,777,100px`

**Comment by clauderic** [comment]
@jeroenransijn this is a known issue, your mileage will vary depending on which browser you're using. `react-virtualized` handles this in a pretty clever way, by "scaling" down the rows that are not currently visible,  but it also leads to a lot of complexity in the code. I deliberately chose to ignore that use-case for `react-tiny-virtual-list` to keep things small and easy to maintain.

See this issue in `react-virtualized` for more context on the matter https://github.com/bvaughn/react-virtualized/issues/396
