### ISSUE TITLE
Height of item

### ISSUE THREAD

**Issue by rahmatkruniawan** [clauderic/react-tiny-virtual-list#9]
Can I set height of my item is dynamically.?
This depency is good I got more 1000 data is works fine.
But when i resize my window to min-wid. If line to ling the go to nextLine so the height of item broken. 
U say height item can be set with function. If cannt set dynamically can u gift some example to use function for height of item

**Comment by clauderic** [comment]
You can pass in a function to `itemSize` which returns the height of an item given its index. Here's a simplified example. You could also dynamically measure the size of the items in advance.

```jsx
import React from 'react';
import {render} from 'react-dom';
import VirtualList from 'react-tiny-virtual-list';

const data = ['A', 'B', 'C', 'D', 'E', 'F', ...];

render(
  <VirtualList
    width='100%'
    height={600}
    itemCount={data.length}
    itemSize={50} // Also supports variable heights (array or function getter)
    renderItem={({index, style}) =>
      <div key={index} style={style}> // The style property contains the item's absolute position
        Letter: {data[index]}, Row: #{index}
      </div>
    }
  />,
  document.getElementById('root')
);
```

When the window resizes, you'll need to call the `recomputeSizes` method on your instance of VirtualList to inform `react-tiny-virtual-list` that the size of your items have changed and should be re-rendered.

**Comment by rahmatkruniawan** [comment]
@clauderic  thanks for response

**Comment by Shaked** [comment]
Hey @clauderic, 

I hope it's ok I am asking, but how would you do this? 
> (for example, you could also dynamically measure the size of the items in advance). 

I have a huge list which includes items with different heights and the content of the items changes everyday. Therefore I have to figure a way of calculating the heights of each of them.

Thank you! 
Shaked

**Comment by MrChe** [comment]
How calculation dynamic height item? I don't have fields height in the object!

**Comment by binglinglanyun** [comment]
any solution for this?
